colorscheme desert

:let mapleader=","
set guifont=Monospace\ 12 

"pathogen
execute pathogen#infect()

syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set number

"lost focus autosave
:au FocusLost * silent! wa
:set autowriteall

"undo
set undofile
set undodir=~/.vimundo/

" cntrl.p
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_max_files = 0

" nerdtree
map <C-n> :NERDTreeToggle<CR>

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['jsxhint']
let g:syntastic_java_checkers=['']

"vim session
let g:session_directory = '~/.vim-sessions'
let g:session_autoload = 'no'

"buffer switching
map <C-TAB> :bnext<CR>
map <C-S-TAB> :bprev<CR>

"cntrl-s for saving
map <C-s> :wa<CR>

"for gf
set suffixesadd+=.js,.jsx
set wildignore+=**/target**
set wildignore+=**/ztest**

"vim project
let g:project_use_nerdtree = 1
set rtp+=~/.vim/bundle/vim-project/
call project#rc("~/git")

source ~/.vimproject.vim

