colorscheme desert

:let mapleader=","
set guifont=Monospace\ 12 

"pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" cntrl.p
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" nerdtree
map <C-n> :NERDTreeToggle<CR>

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['jsxhint']

"vim session
let g:session_directory = '~/.vim-sessions'
let g:session_autoload = 'no'

"buffer switching
map <C-TAB> :bnext<CR>
map <C-S-TAB> :bprev<CR>

"cntrl-s for saving
map <C-s> :wa<CR>

"for gf
set suffixesadd+=.js,.jsx
set wildignore+=**/target**
set wildignore+=**/ztest**

"vim project
set rtp+=~/.vim/bundle/vim-project/
let g:project_use_nerdtree = 1
" custom starting path
call project#rc("~/git")

Project "cjo"
Callback "cjo", "SetPathCjo"
Project "speedyg"
"Callback "speedyg", "SetPathSpeedyg"
Project "simon"
Project "jaws"

function! SetPathSpeedyg(...) abort
  setlocal path=~/git/speedyg/**
endfunction

function! SetPathCjo(...) abort
  setlocal path=~/git/cjo/**
endfunction

